# Generated by Django 6.0.5 on 2026-07-22 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_medicinemodel_patientmodel_age_patientmodel_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
            },
        ),
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=20),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='generic_name',
            field=models.CharField(blank=True, help_text='e.g., Paracetamol', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10, help_text='Triggers low-stock warning'),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g., 500mg, 5ml', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='Management.appointmentmodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='notes',
            field=models.TextField(blank=True, help_text="Doctor's general advice or dietary warnings", null=True),
        ),
        migrations.AlterField(
            model_name='medicinemodel',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicinemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicinemodel',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='Management.doctormodel'),
        ),
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='Management.patientmodel'),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='Management.medicinecategorymodel'),
        ),
        migrations.CreateModel(
            name='PrescriptionItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='e.g., 1-0-1 or 1 tablet every 8 hours', max_length=50)),
                ('duration', models.CharField(help_text='e.g., 5 days', max_length=50)),
                ('instructions', models.CharField(blank=True, help_text='e.g., After food', max_length=150, null=True)),
                ('quantity_prescribed', models.PositiveIntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.medicinemodel')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Management.prescriptionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='Management.medicinemodel')),
            ],
            options={
                'unique_together': {('medicine', 'batch_number')},
            },
        ),
    ]
