# Generated by Django 6.0.5 on 2026-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_alter_usermodel_role_doctorschedulemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('staff', 'Staff'), ('pharmacist', 'Pharmacist'), ('lab', 'Lab')], max_length=20, null=True),
        ),
    ]
