# Generated by Django 6.0.5 on 2026-08-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_medicinecategorymodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='DOB',
        ),
    ]
