# Generated by Django 6.0.5 on 2026-06-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_medicinemodel_alter_appointmentmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
