# Generated by Django 6.0.5 on 2026-06-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_patientmodel_age_alter_patientmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
