# Generated by Django 6.0.5 on 2026-06-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_patientmodel_height_patientmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
